# Generated by Django 4.1.1 on 2022-09-28 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Título')),
                ('telefone', models.CharField(max_length=12, verbose_name='Telefone')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('endereco', models.CharField(max_length=250, verbose_name='Endereco')),
                ('foto', models.ImageField(null=True, upload_to='cliente', verbose_name='Foto')),
            ],
        ),
        migrations.CreateModel(
            name='Emprego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('vagas', models.IntegerField(verbose_name='Vagas')),
                ('empresa', models.CharField(max_length=100, verbose_name='Empresa')),
                ('foto', models.ImageField(null=True, upload_to='emprego', verbose_name='Foto')),
            ],
        ),
    ]
